out_dir: ..\data\processed\pretrain\synthea500
loader:
  concepts: [diagnose, medication]
  data_dir: ..\data\raw\synthea500
  patients_info: patients_info.csv
features:
  age: true
  abspos:
    year: 1900
    month: 1
    day: 26
  binary_segment: true
  background: ['GENDER']
  los: true
split_ratios: 
  train: 0.7
  val: 0.2
  test: 0.1
tokenizer:
  sep_tokens: true
  cls_token: true
  padding: true
  truncation: 100
min_concepts: 2

