out_dir: ..\data\processed\pretrain\synthea
loader:
  concepts: [diagnose, medication]
  data_dir: ..\data\raw\synthea
  patients_info: patients_info.csv
features:
  age: true
  abspos:
    year: 1900
    month: 1
    day: 26
  segment: true
  background: []
split_ratios: 
  train: 0.7
  val: 0.2
  test: 0.1
tokenizer:
  sep_tokens: true
  cls_token: true
  padding: true
  truncation: 100
min_concepts: 2
masked_ratio: 0.15
min_los: 3
