data_dir: ..\data\processed\finetune_death\synthea500

model_path: ..\runs\pretrain_test2\checkpoint_epoch1_end.pt

optimizer:
  lr: 5e-5
  weight_decay: 0
  epsilon: 1e-6

trainer_args:
  batch_size: 32
  effective_batch_size: 128
  epochs: 10
  info: true
  run_name: finetune_death_test

metrics:
  accuracy:
    _target_: evaluation.metrics.Accuracy
  precision:
    _target_: evaluation.metrics.Precision
  recall:
    _target_: evaluation.metrics.Recall
  roc_auc:
    _target_: evaluation.metrics.ROC_AUC