data_dir: ..\data\processed\finetune_death\synthea500

model_path: ..\runs\finetune_death_test\checkpoint_epoch9_end.pt

optimizer:
  lr: 1e-5
  weight_decay: 0
  epsilon: 1e-5

trainer_args:
  batch_size: 32
  # effective_batch_size: 128
  epochs: 10
  info: true
  run_name: perturbation_test

stratification:
  min_age: 20
  max_age: 80
  age_window: 20
  
lambda: 1