data_dir: ..\data\processed\pretrain\synthea500

dataset:
  masked_ratio: 0.15
  plos: false
  min_los: 0
  ignore_special_tokens: true

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 192
  num_hidden_layers: 6
  num_attention_heads: 6
  intermediate_size: 64
optimizer:
  lr: 5e-5
  weight_decay: 0
  epsilon: 1e-6

trainer_args:
  batch_size: 32
  effective_batch_size: 128
  epochs: 5
  info: true
  run_name: pretrain_test2

scheduler:
  num_warmup_steps: 10
  num_training_steps: 100

collate_fn: dynamic_padding

metrics:
  top1:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 5
  top30:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 30
  top50:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 50
  top100:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 100
