train_dataset: ..\data\processed\pretrain\synthea500\dataset.train
val_dataset: ..\data\processed\pretrain\synthea500\dataset.val

model:
  max_position_embeddings: 512
  linear: true
  hidden_size: 192
  num_hidden_layers: 6
  num_attention_heads: 6
  intermediate_size: 64

optimizer:
  lr: 5e-5
  weight_decay: 0
  epsilon: 1e-6

trainer_args:
  batch_size: 32
  effective_batch_size: 128
  epochs: 2
  info: true
  run_name: test2

collate_fn: null

metrics:
  top1:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 1
  top10:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 5
  top30:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 30
  top50:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 50
  top100:
    _target_: evaluation.metrics.PrecisionAtK
    topk: 100
